name = "GDXInterface"
uuid = "b8352055-3412-4df1-864e-ee7edae71aec"
version = "0.1.0"
authors = ["Martin Kirk Bonde", "James Daniel Foster"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
gdx_jll = "aa021fa7-5c7d-5dc1-9fa7-c90cd282ac20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]